
service: overattribution-auth

frameworkVersion: "=1.44.1"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

resources:
  Resources:

    CognitoUserPoolOverAttribution:
      Type: AWS::Cognito::UserPool
      Properties:
        AliasAttributes:
          - email
          - preferred_username
        AutoVerifiedAttributes:
          - email
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: true
          DeviceOnlyRememberedOnUserPrompt: true
        MfaConfiguration: OFF
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 7
        UserPoolName: auth-overattribution-${self:provider.stage}
